export const translations: any = {
  en: {
    "nav.collection": "Collection", "nav.crafts": "Craftsmanship", "nav.custom": "Custom Order",
    "cat.all": "All Products", "cat.coffee": "Coffee Tables", "cat.dining": "Dining Tables", "cat.tv": "TV Stands & Cabinets", "cat.shelving": "Shelving", "cat.kids": "Children's Beds", "cat.benches": "Benches", "cat.chairs": "Oak Chairs", "cat.side": "Side Tables", "cat.radiator": "Radiator Covers", "cat.bathroom": "Bathroom", "cat.pets": "Pet Furniture", "cat.legs": "Table Legs", "cat.search": "Search products...",
    "price.from": "From", "catalog.count": "{n} products", "catalog.empty": "No products match your search.",
    "nav.about": "About", "nav.contact": "Contact", "nav.cta": "Get a Quote",
    "hero.eyebrow": "Handcrafted since 2018 · Ostrava, Czech Republic",
    "hero.title": "Where Oak<br>Becomes <em>Art</em>",
    "hero.desc": "Each piece is crafted from solid European oak by hand. No mass production. No compromises. Only furniture that will outlive generations.",
    "hero.btn1": "View Collection", "hero.btn2": "Our Process",
    "stat.solid": "Solid Oak", "stat.delivery": "EU Delivery", "stat.custom": "Customisable",
    "products.eyebrow": "Our Collection", "products.title": "Every Piece<br>Tells a <em>Story</em>",
    "products.all": "View all products",
    "product.inquire": "Inquire →", "product.addToCart": "Add to Cart", "product.viewDetails": "View Details →",
    "p1.name": "Beskydos Coffee Table", "p1.price": "From 12 542 Kč",
    "p2.name": "El Klasiko Coffee Table", "p2.price": "From 12 542 Kč",
    "p3.name": "ArtTwo Coffee Table", "p3.price": "From 14 882 Kč",
    "p4.name": "Dubkoun Side Table", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Why Arden Wood",
    "craft.title": "Built by Hand.<br><em>Built to Last.</em>",
    "craft.text": "Every table, door, and shelf that leaves our workshop in Ostrava carries the mark of real craft. We select each board personally. We shape every joint. We finish every surface with natural oil — never synthetic coating.",
    "cf1.title": "European Oak", "cf1.text": "Sourced from certified European forests. Aged naturally, not kiln-dried in haste.",
    "cf2.title": "Custom Made", "cf2.text": "Any dimension. Any finish. Any quantity. We work to your exact specification.",
    "cf3.title": "EU Delivery", "cf3.text": "We ship across Europe. Works with architects, developers, and private clients.",
    "cf4.title": "Lifetime Quality", "cf4.text": "Solid oak furniture gains character with age. This is not furniture you replace.",
    "lang.eyebrow": "Available in your language", "lang.title": "We Speak<br><em>Your Language</em>",
    "cta.eyebrow": "Ready to Order?", "cta.title": "Your <em>Perfect</em><br>Piece Awaits",
    "cta.subtitle": "Tell us what you have in mind. We reply within 24 hours in your language.",
    "cta.email": "Your email address", "cta.send": "Send Request",
    "cta.note": "No commitment. Free consultation. We reply in your language.",
    "footer.tagline": "Handcrafted oak furniture from the heart of Europe. Delivered across the EU.",
    "footer.products": "Products", "footer.info": "Information", "footer.contact": "Contact",
    "fp.tables": "Tables", "fp.doors": "Doors", "fp.shelving": "Shelving", "fp.kitchen": "Kitchen", "fp.custom": "Custom",
    "fi.about": "About Us", "fi.process": "Our Process", "fi.delivery": "Delivery", "fi.care": "Wood Care", "fi.faq": "FAQ",
    "fc.quote": "Get a Quote"
  },
  de: {
    "nav.collection": "Kollektion", "nav.crafts": "Handwerk", "nav.custom": "Sonderanfertigung",
    "cat.all": "Alle Produkte", "cat.coffee": "Couchtische", "cat.dining": "Esstische", "cat.tv": "TV-Möbel & Kommoden", "cat.shelving": "Regale", "cat.kids": "Kinderbetten", "cat.benches": "Sitzbänke", "cat.chairs": "Eichenstühle", "cat.side": "Beistelltische", "cat.radiator": "Heizkörperverkleidungen", "cat.bathroom": "Bad", "cat.pets": "Haustiermöbel", "cat.legs": "Tischgestelle", "cat.search": "Produkte suchen...",
    "price.from": "Ab", "catalog.count": "{n} Produkte", "catalog.empty": "Keine Produkte gefunden.",
    "nav.about": "Über uns", "nav.contact": "Kontakt", "nav.cta": "Angebot anfragen",
    "hero.eyebrow": "Handgefertigt seit 2018 · Ostrava, Tschechien",
    "hero.title": "Wo Eiche zur<br><em>Kunst</em> wird",
    "hero.desc": "Jedes Stück wird aus massiver europäischer Eiche von Hand gefertigt. Keine Massenproduktion. Keine Kompromisse. Nur Möbel, die Generationen überdauern.",
    "hero.btn1": "Kollektion ansehen", "hero.btn2": "Unser Prozess",
    "stat.solid": "Massiveiche", "stat.delivery": "EU-Lieferung", "stat.custom": "Maßgefertigt",
    "products.eyebrow": "Unsere Kollektion", "products.title": "Jedes Stück<br>erzählt eine <em>Geschichte</em>",
    "products.all": "Alle Produkte",
    "product.inquire": "Anfragen →", "product.addToCart": "In den Warenkorb", "product.viewDetails": "Details ansehen →",
    "p1.name": "Beskydos Couchtisch", "p1.price": "Ab 12 542 Kč",
    "p2.name": "El Klasiko Couchtisch", "p2.price": "Ab 12 542 Kč",
    "p3.name": "ArtTwo Couchtisch", "p3.price": "Ab 14 882 Kč",
    "p4.name": "Dubkoun Beistelltisch", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Warum Arden Wood",
    "craft.title": "Von Hand gebaut.<br><em>Für die Ewigkeit.</em>",
    "craft.text": "Jeder Tisch, jede Tür und jedes Regal, das unsere Werkstatt in Ostrava verlässt, trägt das Zeichen echter Handwerkskunst. Wir wählen jedes Brett persönlich aus.",
    "cf1.title": "Europäische Eiche", "cf1.text": "Aus zertifizierten europäischen Wäldern. Natürlich getrocknet.",
    "cf2.title": "Maßanfertigung", "cf2.text": "Jedes Maß, jede Oberfläche, jede Menge. Nach Ihren Vorgaben.",
    "cf3.title": "EU-Lieferung", "cf3.text": "Wir liefern europaweit. Für Architekten, Bauträger und Privatkunden.",
    "cf4.title": "Lebenslange Qualität", "cf4.text": "Massivholzmöbel gewinnen mit dem Alter. Das sind keine Möbel, die man ersetzt.",
    "lang.eyebrow": "In Ihrer Sprache verfügbar", "lang.title": "Wir sprechen<br><em>Ihre Sprache</em>",
    "cta.eyebrow": "Bereit zu bestellen?", "cta.title": "Ihr <em>perfektes</em><br>Stück wartet",
    "cta.subtitle": "Teilen Sie uns Ihre Vorstellung mit. Wir antworten innerhalb von 24 Stunden.",
    "cta.email": "Ihre E-Mail-Adresse", "cta.send": "Anfrage senden",
    "cta.note": "Unverbindlich. Kostenlose Beratung. Wir antworten auf Deutsch.",
    "footer.tagline": "Handgefertigte Eichenmöbel aus dem Herzen Europas. EU-weite Lieferung.",
    "footer.products": "Produkte", "footer.info": "Informationen", "footer.contact": "Kontakt",
    "fp.tables": "Tische", "fp.doors": "Türen", "fp.shelving": "Regale", "fp.kitchen": "Küche", "fp.custom": "Sonderanfertigung",
    "fi.about": "Über uns", "fi.process": "Unser Prozess", "fi.delivery": "Lieferung", "fi.care": "Holzpflege", "fi.faq": "FAQ",
    "fc.quote": "Angebot anfragen"
  },
  fr: {
    "nav.collection": "Collection", "nav.crafts": "Savoir-faire", "nav.custom": "Sur mesure",
    "cat.all": "Tous les produits", "cat.coffee": "Tables basses", "cat.dining": "Tables à manger", "cat.tv": "Meubles TV & commodes", "cat.shelving": "Étagères", "cat.kids": "Lits enfant", "cat.benches": "Bancs", "cat.chairs": "Chaises en chêne", "cat.side": "Tables d'appoint", "cat.radiator": "Caches-radiateurs", "cat.bathroom": "Salle de bain", "cat.pets": "Meubles pour animaux", "cat.legs": "Pieds de table", "cat.search": "Rechercher des produits...",
    "price.from": "À partir de", "catalog.count": "{n} produits", "catalog.empty": "Aucun produit trouvé.",
    "nav.about": "À propos", "nav.contact": "Contact", "nav.cta": "Demander un devis",
    "hero.eyebrow": "Artisanat depuis 2018 · Ostrava, République tchèque",
    "hero.title": "Là où le Chêne<br>devient <em>Art</em>",
    "hero.desc": "Chaque pièce est fabriquée à la main en chêne massif européen. Aucune production de masse. Aucun compromis. Uniquement des meubles qui traverseront les générations.",
    "hero.btn1": "Voir la collection", "hero.btn2": "Notre processus",
    "stat.solid": "Chêne massif", "stat.delivery": "Livraison UE", "stat.custom": "Sur mesure",
    "products.eyebrow": "Notre Collection", "products.title": "Chaque pièce<br>raconte une <em>histoire</em>",
    "products.all": "Tous les produits",
    "product.inquire": "Renseignements →", "product.addToCart": "Ajouter au panier", "product.viewDetails": "Voir les détails →",
    "p1.name": "Table basse Beskydos", "p1.price": "À partir de 12 542 Kč",
    "p2.name": "Table basse El Klasiko", "p2.price": "À partir de 12 542 Kč",
    "p3.name": "Table basse ArtTwo", "p3.price": "À partir de 14 882 Kč",
    "p4.name": "Table d'appoint Dubkoun", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Pourquoi Arden Wood",
    "craft.title": "Fait à la main.<br><em>Fait pour durer.</em>",
    "craft.text": "Chaque table, porte et étagère qui quitte notre atelier d'Ostrava porte la marque du vrai artisanat. Nous sélectionnons chaque planche personnellement.",
    "cf1.title": "Chêne européen", "cf1.text": "Issu de forêts européennes certifiées. Séché naturellement.",
    "cf2.title": "Sur mesure", "cf2.text": "Toute dimension, toute finition, toute quantité. Selon vos spécifications.",
    "cf3.title": "Livraison UE", "cf3.text": "Nous livrons dans toute l'Europe. Architectes, promoteurs et particuliers.",
    "cf4.title": "Qualité à vie", "cf4.text": "Le mobilier en chêne massif gagne en caractère avec l'âge.",
    "lang.eyebrow": "Disponible dans votre langue", "lang.title": "Nous parlons<br><em>votre langue</em>",
    "cta.eyebrow": "Prêt à commander?", "cta.title": "Votre pièce <em>parfaite</em><br>vous attend",
    "cta.subtitle": "Dites-nous ce que vous souhaitez. Nous répondons sous 24h dans votre langue.",
    "cta.email": "Votre adresse email", "cta.send": "Envoyer la demande",
    "cta.note": "Sans engagement. Consultation gratuite. Réponse en français.",
    "footer.tagline": "Mobilier en chêne massif du cœur de l'Europe. Livraison dans toute l'UE.",
    "footer.products": "Produits", "footer.info": "Informations", "footer.contact": "Contact",
    "fp.tables": "Tables", "fp.doors": "Portes", "fp.shelving": "Étagères", "fp.kitchen": "Cuisine", "fp.custom": "Sur mesure",
    "fi.about": "À propos", "fi.process": "Notre processus", "fi.delivery": "Livraison", "fi.care": "Entretien", "fi.faq": "FAQ",
    "fc.quote": "Demander un devis"
  },
  cs: {
    "nav.collection": "Kolekce", "nav.crafts": "Řemeslo", "nav.custom": "Na zakázku",
    "cat.all": "Všechny produkty", "cat.coffee": "Konferenční stolky", "cat.dining": "Jídelní stoly", "cat.tv": "TV stolky a skříně", "cat.shelving": "Police a regály", "cat.kids": "Dětské postele", "cat.benches": "Lavice", "cat.chairs": "Dubové židle", "cat.side": "Odkládací stolky", "cat.radiator": "Kryty na radiátor", "cat.bathroom": "Koupelna", "cat.pets": "Domácí mazlíčci", "cat.legs": "Podnože", "cat.search": "Hledat produkty...",
    "price.from": "Od", "catalog.count": "{n} produktů", "catalog.empty": "Žádné produkty neodpovídají hledání.",
    "nav.about": "O nás", "nav.contact": "Kontakt", "nav.cta": "Poptat cenu",
    "hero.eyebrow": "Ručně vyráběno od 2018 · Ostrava, Česká republika",
    "hero.title": "Kde Dub<br>se stává <em>Uměním</em>",
    "hero.desc": "Každý kus je ručně vyroben z masivního evropského dubu. Žádná sériová výroba. Žádné kompromisy. Jen nábytek, který přežije generace.",
    "hero.btn1": "Prohlédnout kolekci", "hero.btn2": "Náš proces",
    "stat.solid": "Masivní dub", "stat.delivery": "Doručení EU", "stat.custom": "Na zakázku",
    "products.eyebrow": "Naše Kolekce", "products.title": "Každý kus<br>vypráví <em>příběh</em>",
    "products.all": "Všechny produkty",
    "product.inquire": "Poptat →", "product.addToCart": "Do košíku", "product.viewDetails": "Zobrazit detail →",
    "p1.name": "Konferenční stůl Beskydos", "p1.price": "Od 12 542 Kč",
    "p2.name": "Konferenční stůl El Klasiko", "p2.price": "Od 12 542 Kč",
    "p3.name": "Konferenční stůl ArtTwo", "p3.price": "Od 14 882 Kč",
    "p4.name": "Odkládací stolek Dubkoun", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Proč Arden Wood",
    "craft.title": "Vyrobeno ručně.<br><em>Vyrobeno navěky.</em>",
    "craft.text": "Každý stůl, dveře a polička, které opustí naši dílnu v Ostravě, nesou pečeť skutečného řemesla. Každé prkno vybíráme osobně.",
    "cf1.title": "Evropský dub", "cf1.text": "Z certifikovaných evropských lesů. Přirozeně vysušený.",
    "cf2.title": "Na zakázku", "cf2.text": "Jakýkoliv rozměr, povrch, množství. Přesně podle vašich požadavků.",
    "cf3.title": "Doručení EU", "cf3.text": "Dodáváme po celé Evropě. Pro architekty, developery i soukromé klienty.",
    "cf4.title": "Celoživotní kvalita", "cf4.text": "Masivní dubový nábytek získává s věkem charakter. To není nábytek, který nahrazujete.",
    "lang.eyebrow": "Dostupné ve vašem jazyce", "lang.title": "Mluvíme<br><em>vaším jazykem</em>",
    "cta.eyebrow": "Připraveni objednat?", "cta.title": "Váš <em>dokonalý</em><br>kus čeká",
    "cta.subtitle": "Řekněte nám, co máte na mysli. Odpovíme do 24 hodin ve vašem jazyce.",
    "cta.email": "Vaše e-mailová adresa", "cta.send": "Odeslat poptávku",
    "cta.note": "Bez závazku. Bezplatná konzultace. Odpovídáme česky.",
    "footer.tagline": "Ručně vyráběný dubový nábytek ze srdce Evropy. Doručení po celé EU.",
    "footer.products": "Produkty", "footer.info": "Informace", "footer.contact": "Kontakt",
    "fp.tables": "Stoly", "fp.doors": "Dveře", "fp.shelving": "Police", "fp.kitchen": "Kuchyně", "fp.custom": "Na zakázku",
    "fi.about": "O nás", "fi.process": "Náš proces", "fi.delivery": "Doručení", "fi.care": "Péče o dřevo", "fi.faq": "FAQ",
    "fc.quote": "Poptat cenu"
  },
  pl: {
    "nav.collection": "Kolekcja", "nav.crafts": "Rzemiosło", "nav.custom": "Na zamówienie",
    "cat.all": "Wszystkie produkty", "cat.coffee": "Stoliki kawowe", "cat.dining": "Stoły jadalniane", "cat.tv": "Szafki RTV i komody", "cat.shelving": "Półki i regały", "cat.kids": "Łóżka dziecięce", "cat.benches": "Ławki", "cat.chairs": "Krzesła dębowe", "cat.side": "Stoliki pomocnicze", "cat.radiator": "Osłony na grzejnik", "cat.bathroom": "Łazienka", "cat.pets": "Meble dla zwierząt", "cat.legs": "Nogi do stołów", "cat.search": "Szukaj produktów...",
    "price.from": "Od", "catalog.count": "{n} produktów", "catalog.empty": "Brak produktów spełniających kryteria.",
    "nav.about": "O nas", "nav.contact": "Kontakt", "nav.cta": "Zapytaj o cenę",
    "hero.eyebrow": "Ręcznie wykonane od 2018 · Ostrava, Czechy",
    "hero.title": "Gdzie Dąb<br>staje się <em>Sztuką</em>",
    "hero.desc": "Każdy mebel wykonany jest ręcznie z litego europejskiego dębu. Bez masowej produkcji. Bez kompromisów. Meble, które przetrwają pokolenia.",
    "hero.btn1": "Zobacz kolekcję", "hero.btn2": "Nasz proces",
    "stat.solid": "Lity dąb", "stat.delivery": "Dostawa UE", "stat.custom": "Na zamówienie",
    "products.eyebrow": "Nasza Kolekcja", "products.title": "Każdy mebel<br>opowiada <em>historię</em>",
    "products.all": "Wszystkie produkty",
    "product.inquire": "Zapytaj →", "product.addToCart": "Do koszyka", "product.viewDetails": "Zobacz szczegóły →",
    "p1.name": "Stolik kawowy Beskydos", "p1.price": "Od 12 542 Kč",
    "p2.name": "Stolik kawowy El Klasiko", "p2.price": "Od 12 542 Kč",
    "p3.name": "Stolik kawowy ArtTwo", "p3.price": "Od 14 882 Kč",
    "p4.name": "Stolik pomocniczy Dubkoun", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Dlaczego Arden Wood",
    "craft.title": "Zrobione ręcznie.<br><em>Zrobione na wieki.</em>",
    "craft.text": "Każdy stół, drzwi i półka opuszczające nasz warsztat w Ostrawie noszą znamię prawdziwego rzemiosła.",
    "cf1.title": "Europejski dąb", "cf1.text": "Z certyfikowanych lasów europejskich. Naturalnie sezonowany.",
    "cf2.title": "Na zamówienie", "cf2.text": "Dowolny wymiar, wykończenie, ilość. Według Twoich specyfikacji.",
    "cf3.title": "Dostawa UE", "cf3.text": "Dostarczamy w całej Europie. Dla architektów, deweloperów i klientów prywatnych.",
    "cf4.title": "Jakość na całe życie", "cf4.text": "Meble z litego dębu zyskują charakter z wiekiem.",
    "lang.eyebrow": "Dostępne w Twoim języku", "lang.title": "Mówimy<br><em>Twoim językiem</em>",
    "cta.eyebrow": "Gotowy do zamówienia?", "cta.title": "Twój <em>idealny</em><br>mebel czeka",
    "cta.subtitle": "Powiedz nam, czego szukasz. Odpowiadamy w ciągu 24 godzin po polsku.",
    "cta.email": "Twój adres e-mail", "cta.send": "Wyślij zapytanie",
    "cta.note": "Bez zobowiązań. Bezpłatna konsultacja. Odpowiadamy po polsku.",
    "footer.tagline": "Ręcznie wykonane meble dębowe z serca Europy. Dostawa w całej UE.",
    "footer.products": "Produkty", "footer.info": "Informacje", "footer.contact": "Kontakt",
    "fp.tables": "Stoły", "fp.doors": "Drzwi", "fp.shelving": "Półki", "fp.kitchen": "Kuchnia", "fp.custom": "Na zamówienie",
    "fi.about": "O nas", "fi.process": "Nasz proces", "fi.delivery": "Dostawa", "fi.care": "Pielęgnacja drewna", "fi.faq": "FAQ",
    "fc.quote": "Zapytaj o cenę"
  },
  it: {
    "nav.collection": "Collezione", "nav.crafts": "Artigianato", "nav.custom": "Su misura",
    "cat.all": "Tutti i prodotti", "cat.coffee": "Tavolini", "cat.dining": "Tavoli da pranzo", "cat.tv": "Mobili TV e credenze", "cat.shelving": "Mensole", "cat.kids": "Letti per bambini", "cat.benches": "Panche", "cat.chairs": "Sedie in rovere", "cat.side": "Tavolini d'appoggio", "cat.radiator": "Copri radiatori", "cat.bathroom": "Bagno", "cat.pets": "Mobili per animali", "cat.legs": "Gambe per tavoli", "cat.search": "Cerca prodotti...",
    "price.from": "Da", "catalog.count": "{n} prodotti", "catalog.empty": "Nessun prodotto trovato.",
    "nav.about": "Chi siamo", "nav.contact": "Contatti", "nav.cta": "Richiedi preventivo",
    "hero.eyebrow": "Fatto a mano dal 2018 · Ostrava, Repubblica Ceca",
    "hero.title": "Dove la Quercia<br>diventa <em>Arte</em>",
    "hero.desc": "Ogni pezzo è realizzato a mano in rovere massello europeo. Nessuna produzione di massa. Nessun compromesso. Solo mobili che dureranno generazioni.",
    "hero.btn1": "Vedi la collezione", "hero.btn2": "Il nostro processo",
    "stat.solid": "Rovere massello", "stat.delivery": "Consegna UE", "stat.custom": "Su misura",
    "products.eyebrow": "La Nostra Collezione", "products.title": "Ogni pezzo<br>racconta una <em>storia</em>",
    "products.all": "Tutti i prodotti", "product.inquire": "Richiedi →", "product.addToCart": "Aggiungi al carrello", "product.viewDetails": "Vedi dettagli →",
    "p1.name": "Tavolino Beskydos", "p1.price": "Da 12 542 Kč",
    "p2.name": "Tavolino El Klasiko", "p2.price": "Da 12 542 Kč",
    "p3.name": "Tavolino ArtTwo", "p3.price": "Da 14 882 Kč",
    "p4.name": "Tavolino d'appoggio Dubkoun", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Perché Arden Wood",
    "craft.title": "Fatto a mano.<br><em>Fatto per durare.</em>",
    "craft.text": "Ogni tavolo, porta e scaffale che esce dal nostro laboratorio a Ostrava porta il segno della vera artigianalità.",
    "cf1.title": "Rovere europeo", "cf1.text": "Da foreste europee certificate. Stagionato naturalmente.",
    "cf2.title": "Su misura", "cf2.text": "Qualsiasi dimensione, finitura, quantità. Secondo le vostre specifiche.",
    "cf3.title": "Consegna UE", "cf3.text": "Consegniamo in tutta Europa. Per architetti, developer e privati.",
    "cf4.title": "Qualità a vita", "cf4.text": "I mobili in rovere massello acquistano carattere con l'età.",
    "lang.eyebrow": "Disponibile nella tua lingua", "lang.title": "Parliamo<br><em>la tua lingua</em>",
    "cta.eyebrow": "Pronto ad ordinare?", "cta.title": "Il tuo <em>pezzo perfetto</em><br>ti aspetta",
    "cta.subtitle": "Dicci cosa desideri. Rispondiamo entro 24 ore nella tua lingua.",
    "cta.email": "Il tuo indirizzo email", "cta.send": "Invia richiesta",
    "cta.note": "Senza impegno. Consulenza gratuita. Risposta in italiano.",
    "footer.tagline": "Mobili in rovere massello dal cuore d'Europa. Consegna in tutta l'UE.",
    "footer.products": "Prodotti", "footer.info": "Informazioni", "footer.contact": "Contatti",
    "fp.tables": "Tavoli", "fp.doors": "Porte", "fp.shelving": "Scaffali", "fp.kitchen": "Cucina", "fp.custom": "Su misura",
    "fi.about": "Chi siamo", "fi.process": "Il nostro processo", "fi.delivery": "Consegna", "fi.care": "Cura del legno", "fi.faq": "FAQ",
    "fc.quote": "Richiedi preventivo"
  },
  es: {
    "nav.collection": "Colección", "nav.crafts": "Artesanía", "nav.custom": "A medida",
    "cat.all": "Todos los productos", "cat.coffee": "Mesas de centro", "cat.dining": "Mesas de comedor", "cat.tv": "Muebles TV y cómodas", "cat.shelving": "Estanterías", "cat.kids": "Camas infantiles", "cat.benches": "Bancos", "cat.chairs": "Sillas de roble", "cat.side": "Mesas auxiliares", "cat.radiator": "Cubre radiadores", "cat.bathroom": "Baño", "cat.pets": "Muebles para mascotas", "cat.legs": "Patas de mesa", "cat.search": "Buscar productos...",
    "price.from": "Desde", "catalog.count": "{n} productos", "catalog.empty": "No se encontraron productos.",
    "nav.about": "Nosotros", "nav.contact": "Contacto", "nav.cta": "Pedir presupuesto",
    "hero.eyebrow": "Hecho a mano desde 2018 · Ostrava, República Checa",
    "hero.title": "Donde el Roble<br>se convierte en <em>Arte</em>",
    "hero.desc": "Cada pieza está fabricada a mano en roble macizo europeo. Sin producción en masa. Sin compromisos. Solo muebles que durarán generaciones.",
    "hero.btn1": "Ver colección", "hero.btn2": "Nuestro proceso",
    "stat.solid": "Roble macizo", "stat.delivery": "Envío UE", "stat.custom": "A medida",
    "products.eyebrow": "Nuestra Colección", "products.title": "Cada pieza<br>cuenta una <em>historia</em>",
    "products.all": "Todos los productos", "product.inquire": "Consultar →", "product.addToCart": "Añadir al carrito", "product.viewDetails": "Ver detalles →",
    "p1.name": "Mesa de centro Beskydos", "p1.price": "Desde 12 542 Kč",
    "p2.name": "Mesa de centro El Klasiko", "p2.price": "Desde 12 542 Kč",
    "p3.name": "Mesa de centro ArtTwo", "p3.price": "Desde 14 882 Kč",
    "p4.name": "Mesa auxiliar Dubkoun", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Por qué Arden Wood",
    "craft.title": "Hecho a mano.<br><em>Hecho para durar.</em>",
    "craft.text": "Cada mesa, puerta y estante que sale de nuestro taller en Ostrava lleva la marca del verdadero artesanato.",
    "cf1.title": "Roble europeo", "cf1.text": "De bosques europeos certificados. Secado naturalmente.",
    "cf2.title": "A medida", "cf2.text": "Cualquier dimensión, acabado, cantidad. Según sus especificaciones.",
    "cf3.title": "Envío UE", "cf3.text": "Enviamos por toda Europa. Para arquitectos, promotores y particulares.",
    "cf4.title": "Calidad de por vida", "cf4.text": "Los muebles de roble macizo ganan carácter con la edad.",
    "lang.eyebrow": "Disponible en su idioma", "lang.title": "Hablamos<br><em>su idioma</em>",
    "cta.eyebrow": "¿Listo para pedir?", "cta.title": "Su pieza <em>perfecta</em><br>le espera",
    "cta.subtitle": "Cuéntenos lo que necesita. Respondemos en 24 horas en su idioma.",
    "cta.email": "Su dirección de correo", "cta.send": "Enviar solicitud",
    "cta.note": "Sin compromiso. Consulta gratuita. Respondemos en español.",
    "footer.tagline": "Muebles de roble macizo del corazón de Europa. Envío a toda la UE.",
    "footer.products": "Productos", "footer.info": "Información", "footer.contact": "Contacto",
    "fp.tables": "Mesas", "fp.doors": "Puertas", "fp.shelving": "Estanterías", "fp.kitchen": "Cocina", "fp.custom": "A medida",
    "fi.about": "Nosotros", "fi.process": "Nuestro proceso", "fi.delivery": "Envío", "fi.care": "Cuidado de la madera", "fi.faq": "FAQ",
    "fc.quote": "Pedir presupuesto"
  },
  nl: {
    "nav.collection": "Collectie", "nav.crafts": "Vakmanschap", "nav.custom": "Op maat",
    "cat.all": "Alle producten", "cat.coffee": "Salontafels", "cat.dining": "Eettafels", "cat.tv": "Tv-meubels & dressoirs", "cat.shelving": "Wandplanken", "cat.kids": "Kinderbedden", "cat.benches": "Banken", "cat.chairs": "Eiken stoelen", "cat.side": "Bijzettafels", "cat.radiator": "Radiatorombouwen", "cat.bathroom": "Badkamer", "cat.pets": "Huisdierenmeubels", "cat.legs": "Tafelpoten", "cat.search": "Producten zoeken...",
    "price.from": "Vanaf", "catalog.count": "{n} producten", "catalog.empty": "Geen producten gevonden.",
    "nav.about": "Over ons", "nav.contact": "Contact", "nav.cta": "Offerte aanvragen",
    "hero.eyebrow": "Handgemaakt sinds 2018 · Ostrava, Tsjechië",
    "hero.title": "Waar Eik<br><em>Kunst</em> wordt",
    "hero.desc": "Elk stuk wordt met de hand vervaardigd uit massief Europees eikenhout. Geen massaproductie. Geen compromissen. Meubilair dat generaties meegaat.",
    "hero.btn1": "Bekijk collectie", "hero.btn2": "Ons proces",
    "stat.solid": "Massief eiken", "stat.delivery": "EU-levering", "stat.custom": "Op maat",
    "products.eyebrow": "Onze Collectie", "products.title": "Elk stuk<br>vertelt een <em>verhaal</em>",
    "products.all": "Alle producten", "product.inquire": "Informeren →", "product.addToCart": "In winkelwagen", "product.viewDetails": "Bekijk details →",
    "p1.name": "Beskydos salontafel", "p1.price": "Vanaf 12 542 Kč",
    "p2.name": "El Klasiko salontafel", "p2.price": "Vanaf 12 542 Kč",
    "p3.name": "ArtTwo salontafel", "p3.price": "Vanaf 14 882 Kč",
    "p4.name": "Dubkoun bijzettafeltje", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Waarom Arden Wood",
    "craft.title": "Met de hand gemaakt.<br><em>Gemaakt om te duren.</em>",
    "craft.text": "Elk tafel, deur en rek dat onze werkplaats in Ostrava verlaat, draagt het stempel van echt vakmanschap.",
    "cf1.title": "Europees eiken", "cf1.text": "Uit gecertificeerde Europese bossen. Natuurlijk gedroogd.",
    "cf2.title": "Op maat", "cf2.text": "Elke afmeting, afwerking, hoeveelheid. Volgens uw specificaties.",
    "cf3.title": "EU-levering", "cf3.text": "Wij leveren door heel Europa. Voor architecten, ontwikkelaars en particulieren.",
    "cf4.title": "Levenslange kwaliteit", "cf4.text": "Massief eikenhouten meubels krijgen karakter met de leeftijd.",
    "lang.eyebrow": "Beschikbaar in uw taal", "lang.title": "Wij spreken<br><em>uw taal</em>",
    "cta.eyebrow": "Klaar om te bestellen?", "cta.title": "Uw <em>perfecte</em><br>stuk wacht",
    "cta.subtitle": "Vertel ons wat u zoekt. Wij antwoorden binnen 24 uur in uw taal.",
    "cta.email": "Uw e-mailadres", "cta.send": "Verzoek verzenden",
    "cta.note": "Vrijblijvend. Gratis advies. Antwoord in het Nederlands.",
    "footer.tagline": "Handgemaakt eikenhouten meubilair uit het hart van Europa. EU-levering.",
    "footer.products": "Producten", "footer.info": "Informatie", "footer.contact": "Contact",
    "fp.tables": "Tafels", "fp.doors": "Deuren", "fp.shelving": "Kasten", "fp.kitchen": "Keuken", "fp.custom": "Op maat",
    "fi.about": "Over ons", "fi.process": "Ons proces", "fi.delivery": "Levering", "fi.care": "Houtonderhoud", "fi.faq": "FAQ",
    "fc.quote": "Offerte aanvragen"
  },
  sk: {
    "nav.collection": "Kolekcia", "nav.crafts": "Remeslo", "nav.custom": "Na objednávku",
    "cat.all": "Všetky produkty", "cat.coffee": "Konferenčné stolíky", "cat.dining": "Jedálenské stoly", "cat.tv": "TV stolíky a skrine", "cat.shelving": "Police a regály", "cat.kids": "Detské postele", "cat.benches": "Lavice", "cat.chairs": "Dubové stoličky", "cat.side": "Odkladacie stolíky", "cat.radiator": "Kryty na radiátor", "cat.bathroom": "Kúpeľňa", "cat.pets": "Mobiliár pre domáce zvieratá", "cat.legs": "Podnože", "cat.search": "Hľadať produkty...",
    "price.from": "Od", "catalog.count": "{n} produktov", "catalog.empty": "Žiadne produkty nezodpovedajú hľadaniu.",
    "nav.about": "O nás", "nav.contact": "Kontakt", "nav.cta": "Pýtať cenu",
    "hero.eyebrow": "Ručne vyrobené od 2018 · Ostrava, Česká republika",
    "hero.title": "Kde Dub<br>sa stáva <em>Umením</em>",
    "hero.desc": "Každý kus je ručne vyrobený z masívneho európskeho duba. Žiadna sériová výroba. Žiadne kompromisy. Nábytok pre generácie.",
    "hero.btn1": "Pozrieť kolekciu", "hero.btn2": "Náš postup",
    "stat.solid": "Masívny dub", "stat.delivery": "Doručenie EÚ", "stat.custom": "Na objednávku",
    "products.eyebrow": "Naša Kolekcia", "products.title": "Každý kus<br>rozpráva <em>príbeh</em>",
    "products.all": "Všetky produkty", "product.inquire": "Dopyt →", "product.addToCart": "Do košíka", "product.viewDetails": "Zobraziť detail →",
    "p1.name": "Konferenčný stôl Beskydos", "p1.price": "Od 12 542 Kč",
    "p2.name": "Konferenčný stôl El Klasiko", "p2.price": "Od 12 542 Kč",
    "p3.name": "Konferenčný stôl ArtTwo", "p3.price": "Od 14 882 Kč",
    "p4.name": "Odkladací stolík Dubkoun", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Prečo Arden Wood",
    "craft.title": "Vyrobené ručne.<br><em>Vyrobené navždy.</em>",
    "craft.text": "Každý stôl, dvere a polica, ktoré opustia našu dielňu v Ostrave, nesú pečať skutočného remesla.",
    "cf1.title": "Európsky dub", "cf1.text": "Z certifikovaných európskych lesov. Prirodzene vysušený.",
    "cf2.title": "Na objednávku", "cf2.text": "Akýkoľvek rozmer, povrch, množstvo. Presne podľa vašich požiadaviek.",
    "cf3.title": "Doručenie EÚ", "cf3.text": "Dodávame po celej Európe. Pre architektov, developerov a súkromných klientov.",
    "cf4.title": "Celoživotná kvalita", "cf4.text": "Masívny dubový nábytok získava s vekom charakter.",
    "lang.eyebrow": "Dostupné vo vašom jazyku", "lang.title": "Hovoríme<br><em>vaším jazykom</em>",
    "cta.eyebrow": "Pripravení objednať?", "cta.title": "Váš <em>dokonalý</em><br>kus čaká",
    "cta.subtitle": "Povedzte nám, čo hľadáte. Odpovieme do 24 hodín vo vašom jazyku.",
    "cta.email": "Vaša e-mailová adresa", "cta.send": "Odoslať dopyt",
    "cta.note": "Bez záväzku. Bezplatná konzultácia. Odpovedáme po slovensky.",
    "footer.tagline": "Ručne vyrobený dubový nábytok zo srdca Európy. Doručenie po celej EÚ.",
    "footer.products": "Produkty", "footer.info": "Informácie", "footer.contact": "Kontakt",
    "fp.tables": "Stoly", "fp.doors": "Dvere", "fp.shelving": "Police", "fp.kitchen": "Kuchyňa", "fp.custom": "Na objednávku",
    "fi.about": "O nás", "fi.process": "Náš postup", "fi.delivery": "Doručenie", "fi.care": "Starostlivosť o drevo", "fi.faq": "FAQ",
    "fc.quote": "Pýtať cenu"
  },
  uk: {
    "nav.collection": "Колекція", "nav.crafts": "Майстерність", "nav.custom": "На замовлення",
    "cat.all": "Всі товари", "cat.coffee": "Журнальні столики", "cat.dining": "Обідні столи", "cat.tv": "ТВ-тумби та комоди", "cat.shelving": "Полиці та стелажі", "cat.kids": "Дитячі ліжка", "cat.benches": "Лавки", "cat.chairs": "Дубові стільці", "cat.side": "Приставні столики", "cat.radiator": "Накладки на радіатор", "cat.bathroom": "Ванна кімната", "cat.pets": "Меблі для тварин", "cat.legs": "Підножжя для столів", "cat.search": "Пошук товарів...",
    "price.from": "Від", "catalog.count": "{n} товарів", "catalog.empty": "Товарів за вашим запитом не знайдено.",
    "nav.about": "Про нас", "nav.contact": "Контакт", "nav.cta": "Отримати ціну",
    "hero.eyebrow": "Ручна робота з 2018 · Острава, Чехія",
    "hero.title": "Де Дуб<br>стає <em>Мистецтвом</em>",
    "hero.desc": "Кожен виріб виготовлений вручну з масиву європейського дуба. Без серійного виробництва. Без компромісів. Меблі, що переживуть покоління.",
    "hero.btn1": "Переглянути колекцію", "hero.btn2": "Наш процес",
    "stat.solid": "Масив дуба", "stat.delivery": "Доставка ЄС", "stat.custom": "На замовлення",
    "products.eyebrow": "Наша Колекція", "products.title": "Кожен виріб<br>розповідає <em>історію</em>",
    "products.all": "Всі товари", "product.inquire": "Запитати →", "product.addToCart": "У кошик", "product.viewDetails": "Детальніше →",
    "p1.name": "Журнальний стіл «Beskydos»", "p1.price": "Від 12 542 Kč",
    "p2.name": "Журнальний стіл «El Klasiko»", "p2.price": "Від 12 542 Kč",
    "p3.name": "Журнальний стіл «ArtTwo»", "p3.price": "Від 14 882 Kč",
    "p4.name": "Приставний столик «Dubkoun»", "p4.price": "2 170 Kč",
    "craft.eyebrow": "Чому Arden Wood",
    "craft.title": "Зроблено вручну.<br><em>Зроблено назавжди.</em>",
    "craft.text": "Кожен стіл, двері та стелаж, що виходять з нашої майстерні в Остраві, несуть печатку справжнього ремесла. Ми особисто відбираємо кожну дошку.",
    "cf1.title": "Європейський дуб", "cf1.text": "З сертифікованих європейських лісів. Природне сушіння.",
    "cf2.title": "На замовлення", "cf2.text": "Будь-який розмір, покриття, кількість. За вашими вимогами.",
    "cf3.title": "Доставка ЄС", "cf3.text": "Доставляємо по всій Європі. Для архітекторів, забудовників і приватних клієнтів.",
    "cf4.title": "Якість на все життя", "cf4.text": "Меблі з масиву дуба набувають характеру з роками.",
    "lang.eyebrow": "Доступно вашою мовою", "lang.title": "Ми говоримо<br><em>вашою мовою</em>",
    "cta.eyebrow": "Готові замовити?", "cta.title": "Ваш <em>ідеальний</em><br>виріб чекає",
    "cta.subtitle": "Розкажіть нам про свою ідею. Відповідаємо протягом 24 годин вашою мовою.",
    "cta.email": "Ваша електронна пошта", "cta.send": "Надіслати запит",
    "cta.note": "Без зобов'язань. Безкоштовна консультація. Відповідаємо українською.",
    "footer.tagline": "Меблі з масиву дуба ручної роботи з серця Європи. Доставка по всьому ЄС.",
    "footer.products": "Товари", "footer.info": "Інформація", "footer.contact": "Контакт",
    "fp.tables": "Столи", "fp.doors": "Двері", "fp.shelving": "Стелажі", "fp.kitchen": "Кухня", "fp.custom": "На замовлення",
    "fi.about": "Про нас", "fi.process": "Наш процес", "fi.delivery": "Доставка", "fi.care": "Догляд за деревом", "fi.faq": "FAQ",
    "fc.quote": "Отримати ціну"
  }
};

export const PRODUCTS = [
  {n:"Konferenční stolek Beskydos", c:"coffee", p:12542, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/147_f38c2aa3-db17-4686-a28d-75c772065669.png?695e7100", slug:"konferencni-stolek-beskydos-2", hasDetail:true},
  {n:"Konferenční stolek El Klasiko", c:"coffee", p:12542, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/87-2_konferencni-stolek-el-klasiko--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-130-x-70-.jpg?695e70fb", slug:"konferencni-stolek-el-klasiko", hasDetail:true},
  {n:"Konferenční stolek ArtTwo", c:"coffee", p:14882, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/169_konferencni-stolek-arttwo--hrana-desky-rovna--odstin-desky-tmavy-transparentni--velikost-90-.jpg?695e7101", slug:"konferencni-stolek-arttwo", hasDetail:true},
  {n:"Konferenční stolek Král Severu", c:"coffee", p:10728, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/0f704260-6c5f-41b6-8178-66741015dceb.jpg?695e70ef", slug:"konferencni-stolek-kral-severu", hasDetail:true},
  {n:"Konferenční stolek Dubosaurus", c:"coffee", p:12542, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/84-3_konferencni-stolek-dubosaurus--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-130-x-70-.jpg?695e70ff", slug:"konferencni-stolek-dubosaurus", hasDetail:true},
  {n:"Konferenční stolek Duble", c:"coffee", p:10728, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/135_51b6582c-336f-4f11-8d5a-0d2e70eb5af0.jpg?695e70ff", slug:"konferencni-stolek-duble", hasDetail:true},
  {n:"Konferenční stolek Kulaťák", c:"coffee", p:8930, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/102-4_konferencni-stolek-kulatak--hrana-desky-rovna--odstin-desky-tmavy-transparentni--velikost-120-.jpg?695e70fd", slug:"konferencni-stolek-kulatak", hasDetail:true},
  {n:"Konferenční stolek Artuš", c:"coffee", p:10690, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/99-1_7ff30915-61cc-484b-aeb2-41b639713f8f--1.jpg?695e70fc", slug:"konferencni-stolek-artus", hasDetail:true},
  {n:"Konferenční stolek Dřevák", c:"coffee", p:11820, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/96_konferencni-stolek-drevak--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-130-x-70-.jpg?695e70fc", slug:"konferencni-stolek-drevak", hasDetail:true},
  {n:"Konferenční stolek Džimbo", c:"coffee", p:10728, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/93-4_39b7b94d-1148-47e7-91ce-ee73ed95e224.jpg?695e70fc", slug:"konferencni-stolek-dzimbo", hasDetail:true},
  {n:"Konferenční stolek Topství", c:"coffee", p:12542, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/81-3_konferencni-stolek-topstvi--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-130-x-70-.jpg?695e70fa", slug:"konferencni-stolek-topstvi", hasDetail:true},
  {n:"Konferenční stolek Double Duble", c:"coffee", p:12542, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/78-3_konferencni-stolek-double-duble--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-130-x-70-.jpg?695e70fa", slug:"konferencni-stolek-double-duble", hasDetail:true},
  {n:"Jídelní stůl Maximus - do délky 4 METRŮ", c:"dining", p:16913, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/259-19_jidelni-stul-maximus-do-delky-4-metru--hrana-desky-rovna--odstin-desky-tmavy-transparentni--velikost-400-x-100-.jpg?695e7111", slug:"jidelni-stul-maximus-do-delky-4-metru-2", hasDetail:true},
  {n:"Jídelní stůl Beskydos", c:"dining", p:20477, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/256_jidelni-stul-beskydos--hrana-desky-rovna--odstin-desky-tmavy-transparentni--velikost-260-x-100-.jpg?695e710f", slug:"jidelni-stul-beskydos-2", hasDetail:true},
  {n:"Jídelní stůl Spider", c:"dining", p:19071, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/75-1_e1243065-dcb0-424f-86fb-39bb46593990.jpg?695e70f9", slug:"jidelni-stul-spider", hasDetail:true},
  {n:"Jídelní stůl Klasik", c:"dining", p:16913, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/60-5_f1b0f3c9-8f92-4c2a-8678-e6eed044c513.jpg?695e70f4", slug:"jidelni-stul-klasik", hasDetail:true},
  {n:"Jídelní stůl Dubleone", c:"dining", p:16913, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/57-7_jidelni-stul-dubleone--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-160-x-90-.jpg?695e70f2", slug:"jidelni-stul-dubleone", hasDetail:true},
  {n:"Jídelní stůl Džimbo", c:"dining", p:16913, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/54-1_5f66f685-eaa1-4b3a-b469-729ed9351c83-3.jpg?695e70f1", slug:"jidelni-stul-dzimbo", hasDetail:true},
  {n:"Jídelní stůl Valdo", c:"dining", p:20477, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/503-5_jidelni-stul-valdo.jpg?69725ab2", slug:"jidelni-stul-valdo", hasDetail:true},
  {n:"Jídelní stůl Xander", c:"dining", p:18514, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/298-7_01935a05-8452-404c-b084-d58f76bbe490.jpg?695e7113", slug:"jidelni-stul-xander", hasDetail:true},
  {n:"Jídelní stůl Hercules", c:"dining", p:34328, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/232_7ecad9aa-95c2-4f63-8f77-b574318272d3.jpg?695e7105", slug:"jidelni-stul-hercules", hasDetail:true},
  {n:"Jídelní stůl Dřevák", c:"dining", p:17922, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/72-11_jidelni-stul-drevak--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-160-x-90-.jpg?695e70f9", slug:"jidelni-stul-drevak", hasDetail:true},
  {n:"Jídelní stůl The Fošna", c:"dining", p:17922, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/69-3_6c650232-9f00-4b1c-a2a0-591ff3a3a856.jpg?695e70f7", slug:"jidelni-stul-the-fosna", hasDetail:true},
  {n:"Jídelní stůl Happy Hippo", c:"dining", p:22131, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/66-1_7f4f75f2-c108-4126-a5a8-8760702de7d0-2.jpg?695e70f6", slug:"jidelni-stul-happy-hippo", hasDetail:true},
  {n:"Jídelní stůl Král Severu", c:"dining", p:16913, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/51-15_0f704260-6c5f-41b6-8178-66741015dceb.jpg?695e70ef", slug:"jidelni-stul-kral-severu", hasDetail:true},
  {n:"Jídelní stůl Legendary", c:"dining", p:18514, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/48_jidelni-stul-legendary--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-160-x-90-.jpg?695e70ed", slug:"jidelni-stul-legendary", hasDetail:true},
  {n:"KOMODA - Don Komodor", c:"tv", p:31260, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/271_komoda.jpg?695e7112", slug:"don-komodor", hasDetail:true},
  {n:"Stolek pod TV Trámosaurus", c:"tv", p:14658, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/108_stolek-pod-tv-tramosaurus--odstin-desky-tmavy-transparentni--velikost-190-.jpg?695e70fe", slug:"stolek-pod-tv-tramosaurus", hasDetail:true},
  {n:"Skříň pod TV Pandur", c:"tv", p:23898, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/530-7_skrin-pod-tv-pandora--odstin-desky-tmavy-transparentni--velikost-160-.jpg?69f06f78", slug:"skrin-pod-tv-panur", hasDetail:true},
  {n:"Skříň pod TV Pandora", c:"tv", p:23898, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/178_91bf71eb-b418-436a-9ed7-7bc55f5d3ead.jpg?695e7103", slug:"skrin-pod-tv-pandora", hasDetail:true},
  {n:"Dubová deska", c:"tv", p:2816, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/172-3_dubova-deska--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-100-.jpg?695e7103", slug:"dubova-deska", hasDetail:true},
  {n:"Stolek pod TV Dubinátor", c:"tv", p:14658, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/105_aa4ff22f-d1bb-462b-9aec-9a8ce4a6c2f0-6.jpg?695e70fd", slug:"stolek-pod-tv-dubinator", hasDetail:true},
  {n:"Police Dubice", c:"shelving", p:1534, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/114_police-dubice--hrana-desky-prirodni--odstin-desky-tmavy-transparentni--velikost-140-.jpg?695e70ff", slug:"police-dubice", hasDetail:true},
  {n:"Regál Redžinald", c:"shelving", p:15582, f:true, img:"https://www.najodecor.cz/user/categories/orig/748bd29b-6f83-4d3a-b660-fb6455307918.jpg", slug:"regal-redzinald", hasDetail:true},
  {n:"Postel Mareček", c:"kids", p:11650, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/265_postel-marecek_1_.jpg?695e7112", slug:"postel-marecek", hasDetail:true},
  {n:"Patrová postel Viktor", c:"kids", p:25400, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/268_patrova-postel-viktor--velikost-90--200--zabrana-s-predni-zabranou--ulozny-prostor-bez-ulozneho-prostoru.jpg?695e7112", slug:"patrova-postel-viktor", hasDetail:true},
  {n:"Lavice - Král východu", c:"benches", p:3789, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/244-1_b18da582-2c53-466b-aab4-ee73beb74611.jpg?695e7108", slug:"lavice-kral-vychodu", hasDetail:true},
  {n:"Lavice s opěradlem", c:"benches", p:7642, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/506_lavice-s-operadlem.jpg?69725e0c", slug:"lavice-s-operadlem", hasDetail:true},
  {n:"Lavice - Kolmice", c:"benches", p:6062, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/253_lavice-kolmice--hrana-desky-rovna--odstin-desky-tmavy-transparentni--velikost-90-.jpg?695e710d", slug:"lavice-kolmice-2", hasDetail:true},
  {n:"Lavice - Kostka", c:"benches", p:3789, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/250_lavice-kostka--hrana-desky-rovna--odstin-desky-tmavy-transparentni--velikost-90-.jpg?695e710c", slug:"lavice-kostka", hasDetail:true},
  {n:"Lavice - Dřevák", c:"benches", p:6942, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/247_95e9d586-c671-4238-9cdc-0eb28909e229.png?695e710a", slug:"lavice-drevak-2", hasDetail:true},
  {n:"Lavice - happyhippo", c:"benches", p:6942, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/241_8ea89d5e-2eae-4031-b5b6-dc08dab23f99.jpg?695e7106", slug:"lavice-happyhippo", hasDetail:true},
  {n:"Židle Elegance COMFORT dubová", c:"chairs", p:4400, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/466_elegance-comfort.png?695e7113", slug:"zidle-elegance-comfort", hasDetail:false},
  {n:"Dubová židle Victoria", c:"chairs", p:3150, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/detail/478_victoria1.png?695e7113", slug:"dubova-zidle-victoria", hasDetail:false},
  {n:"Barová židle přírodní dub 72cm", c:"chairs", p:4455, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/475_barova-zidle-72.png?695e7113", slug:"barova-zidle-prirodni-dub-72cm", hasDetail:false},
  {n:"Barová židle přírodní dub 63cm", c:"chairs", p:4455, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/detail/472_barova-zidle.png?695e7113", slug:"barova-zidle-prirodni-dub-63cm", hasDetail:false},
  {n:"Židle Elegance Style Dubová", c:"chairs", p:4190, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/469_elegance-style1.jpg?695e7113", slug:"zidle-elegance-style-dubova", hasDetail:false},
  {n:"Židle Elegance Dubová XL rustik", c:"chairs", p:4356, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/463_zidle-elegance-xl-rustik.jpg?695e7113", slug:"zidle-elegance-dubova-xl-rustik", hasDetail:false},
  {n:"Židle Elegance dubová", c:"chairs", p:3800, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/460-2_elegance.png?695e7113", slug:"zidle-elegance", hasDetail:false},
  {n:"Židle duběnka", c:"chairs", p:3959, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/238_0bb18e4b-5fbd-4626-967f-716d2a8cc667.png?695e7105", slug:"zidle-dubenka", hasDetail:false},
  {n:"Barová židle BarBar", c:"chairs", p:4258, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/138-2_be354003-9b56-479e-bcb6-8b21153403b5.jpg?695e70ff", slug:"barova-zidle", hasDetail:false},
  {n:"Odkládací stolek (židlička) Dubkoun", c:"side", p:2170, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/detail/129-3_odkladaci-stolek--zidlicka-dubkoun--odstin-desky-tmavy-transparentni-.jpg?695e70ff", slug:"odkladaci-stolek-dubkoun", hasDetail:true},
  {n:"Dubová kostka", c:"side", p:2762, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/150_8d9f7173-b24e-48a4-8c94-323f66887126.jpg?695e7100", slug:"dubova-kostka", hasDetail:true},
  {n:"Odkládací hrací stoleček (více her)", c:"side", p:3594, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/164_bd702fef-62c4-4f66-b6f9-adab438c78ad.jpg?695e7100", slug:"odkladaci-stolek-sachovnice", hasDetail:true},
  {n:"Odnímatelný kryt na radiátor z masivu", c:"radiator", p:6441, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/484-8_odnimatelny-kryt-na-radiator-z-masivu--delka-190-cm--vyska-80-cm--sirka-15-cm.jpg?695e7116", slug:"odnimatelny-kryt-na-radiator-z-dubu", hasDetail:true},
  {n:"Koupelník", c:"bathroom", p:10037, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/166-1_bd9cfb53-729c-4bcd-bce0-4191654252d5.jpg?695e7101", slug:"koupelnik", hasDetail:true},
  {n:"Stojánek na misky", c:"pets", p:1874, f:true, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/481_stojanek-na-misky--barva-podnozi-cerna--misky-dvojmiskova--odstin-desky-tmavy-transparentni-.jpg?695e7114", slug:"stojanek-na-misky", hasDetail:true},
  {n:"Podnož - MAXIMUS (2ks)", c:"legs", p:4700, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/499_podnoz-maximus.jpg?695e7116", slug:"podnoz-maximus", hasDetail:true},
  {n:"Podnož - SPIDER", c:"legs", p:5530, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/detail/496-2_podnoz-spider-iii.jpg?695e7116", slug:"podnoz-spider", hasDetail:true},
  {n:"Podnož - BESKYDOS", c:"legs", p:5799, f:false, img:"https://cdn.myshoptet.com/usr/www.najodecor.cz/user/shop/big/493_podnoz-beskydos.jpg?695e7116", slug:"podnoz-beskydos", hasDetail:true}
];
